name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
          echo "Hello World"
          echo "Is it just me or is it getting cold out there!!!
      - name: Print goodby
        run: echo "Goodbye, all"
